repos: # pre-commit autoupdate
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: ["--select", "F"]

  - repo: https://github.com/Madoshakalaka/pipenv-setup
    rev: v3.2.0
    hooks:
      - id: pipenv-setup
        additional_dependencies: [".[black]"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

  ## If you want to avoid flake8 errors due to unused vars or imports:
  # - repo: https://github.com/myint/autoflake.git
  #   rev: v1.4
  #   hooks:
  #   - id: autoflake
  #     args: [
  #       --in-place,
  #       --remove-all-unused-imports,
  #       --remove-unused-variables,
  #     ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  ## If like to embrace black styles even in the docs:
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.9.1
  #   hooks:
  #   - id: blacken-docs
  #     additional_dependencies: [black]
